spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=badminton
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15       # Đủ cho 10 luồng batch + 5 luồng API
      minimum-idle: 3             # Luôn giữ 5 connection sẵn sàng để API phản hồi tức thì
      connection-timeout: 30000   # Thời gian tối đa (ms) chờ mượn connection (30 giây)
      max-lifetime: 1800000       # 30 phút. Tránh lỗi PostgreSQL tự động ngắt kết nối quá lâu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  Kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: booking-service-group
      properties:
        spring.json.trusted.packages: "*"
  data :
    redis:
      host: 103.226.249.128
      port: 20091
      password: Dtsgroup@123
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8     # Số lượng kết nối tối đa
          max-idle: 8       # Số kết nối rảnh rỗi tối đa
          min-idle: 2       # Số kết nối rảnh rỗi tối thiểu duy trì
          max-wait: -1ms    # Thời gian chờ khi pool cạn (-1 là chờ vô hạn)

server:
  port: 8083


logging :
  config: classpath:log4j-dev.xml
  level :
    org.springframework.security : DEBUG


